### ISSUE TITLE
[기능 추가 제안]  문제 링크의 색깔을 solved.ac 티어에 맞게 변경

### ISSUE THREAD

**Issue by jihongeek** [dalgors/dalshboard#1]
다른 분들도 그렇게 생각하시는지 모르겠지만 solved.ac 티어 정보가 없어서 일일이 들어가서 확인을 해봐야 하는 번거로움이 약간 있는 것 같습니다.   
그렇다고 해서 solved.ac 아이콘을 넣어버리면 문제 테이블이 넓어 질 것 같기도 합니다. 
  
아무튼 그래서 **문제 링크의 색깔을 solved.ac 티어에 맞게 변경** 되었으면 좋겠습니다.  
(competitions.json에 티어를 추가하고 불러오는 방식으로 하면 좋을 것 같습니다)  

**티어 별 rgb 색코드**
- 브론즈 : rgb(173, 86, 0)
- 실버 : rgb(67, 95, 122)
- 골드 : rgb(236, 154, 0)
- 플레티넘 : rgb(39, 226, 164)
- 다이아몬드 : rgb(0, 180, 252)
- 루비 : rgb(255, 0, 98)

변경 전
![image](https://user-images.githubusercontent.com/34394165/128635024-6093f645-fc3e-4dc0-b2eb-2026833648d6.png)

변경 후 
![image](https://user-images.githubusercontent.com/34394165/128634986-c38d358c-84df-42e7-b466-120c9033b89c.png)

**Comment by solo5star** [comment]
가능하다면 competitions.json 에서 직접 수동으로 추가하지 않고 티어를 표시할 수 있다면 좋겠네요

**Comment by jihongeek** [comment]
> 가능하다면 competitions.json 에서 직접 수동으로 추가하지 않고 티어를 표시할 수 있다면 좋겠네요

넵 competitions.json에 문제를 추가하고  커밋 푸쉬를 하면 github actions workflow로 티어를 크롤링해서 가져와 쓰고 커밋 푸쉬하는 것도 괜찮은 방법이 될 거 같습니다. (계속해서 workflow가 실행되는 것을 방지하기 위해서 특정한 커밋에서만 실행하게 하면 될 거 같습니다)

**Comment by solo5star** [comment]
![image](https://user-images.githubusercontent.com/20203944/128642311-d9ca8f55-cb92-4fc5-9001-6f153a8905ea.png)

새로 브랜치를 하나 만들어야하는데 무심코 메인 브렌치에다가 커밋해버렸네요 ... 아무튼 글자 색보다 배경 색으로 하는 게 더 이뻐보여서 이렇게 바꾸어봤는데 어떨까요?

**Comment by jihongeek** [comment]
와우😮 저는 너무 예쁜 것 같습니다! 티어 세부 레벨에 따라 색이 밝아지는 것도 좋은 아이디어네요!

**Comment by solo5star** [comment]
issue 해결된 것 같으니 close 할께요~~
